In [1]:
import pandas as pd
import numpy as np
import sklearn as skl
from sklearn import preprocessing
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

In [2]:
#load education data
#include 'high school or higher' and 'college or higher' for pop 25+
col_1 = 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over'
col_2 = 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate or higher'
col_3 = "Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree or higher"
education = pd.read_csv('C:/Users/rgale/team_117/data/education.csv',skiprows=1, usecols=['id','Geographic Area Name',col_1,col_2,col_3])
#rename the columns
education = education.rename(columns={col_1:'Population 25+',col_2:'High school graduate or higher',col_3:"Bachelor's degree or higher",'Geographic Area Name':'Location'})
education.head()

,id,Location,Population 25+,High school graduate or higher,Bachelor's degree or higher
0,0500000US01001,"Autauga County, Alabama",37367,33076,766
1,0500000US01003,"Baldwin County, Alabama",151112,137219,1866
2,0500000US01005,"Barbour County, Alabama",17964,13152,254
3,0500000US01007,"Bibb County, Alabama",16168,12782,354
4,0500000US01009,"Blount County, Alabama",39791,32028,498

In [3]:
#add column for percentage of people without a high school degree
education['pct_no_high_school_degree']=((education['Population 25+']-education['High school graduate or higher'].astype('float64'))/education['Population 25+'].astype('float64')*100)

In [4]:
#add column for percentage of people without a bachelor's degree
education['pct_no_college_degree']=((education['Population 25+']-education["Bachelor's degree or higher"].astype('float64'))/education['Population 25+'].astype('float64')*100)

In [5]:
#add FIPS code
fips = []
for county_id in education['id']:
    fips_i = county_id[-5:]
#     print(fips)
    fips.append(fips_i)

In [6]:
education['FIPS'] = fips

In [7]:
education.head()

,id,Location,Population 25+,High school graduate or higher,Bachelor's degree or higher,pct_no_high_school_degree,pct_no_college_degree,FIPS
0,0500000US01001,"Autauga County, Alabama",37367,33076,766,11.483394,97.950063,01001
1,0500000US01003,"Baldwin County, Alabama",151112,137219,1866,9.193843,98.765154,01003
2,0500000US01005,"Barbour County, Alabama",17964,13152,254,26.786907,98.586061,01005
3,0500000US01007,"Bibb County, Alabama",16168,12782,354,20.942603,97.810490,01007
4,0500000US01009,"Blount County, Alabama",39791,32028,498,19.509437,98.748461,01009